### ISSUE TITLE
PhenotypeLibrary Cohort Definition tab information only uses half width

### ISSUE THREAD

**Issue by schuemie** [OHDSI/CohortDiagnostics#312] opened 2020-12-22 08:58 UTC
![Capture](https://user-images.githubusercontent.com/6713328/102869594-20908200-443c-11eb-93de-c4c76c4ceb53.PNG)

It seems to be using columns? 

Also, for some reason the table allows selecting multiple columns. Should be only one.

**Comment by gowthamrao** [comment] 2021-02-17 11:04
@schuemie  this is by design. I have implement cohort comparison, i.e. when two cohorts are selected - a comparison operation is performed and difference in JSON, SQL, text is shown. Also - the two cohorts are presented side by side.

But i see the point of wasted white space. I will solve this by using a conditional check - where the columns will be wider in all cases other than when comparison is happening

**Comment by gowthamrao** [comment] 2021-03-11 01:17
Closing because not a bug

**Closed by gowthamrao** 2021-03-11 01:17 UTC
