### ISSUE TITLE
Fail to launch diagnostics explorer

### ISSUE THREAD

**Issue by SamuelFan1215** [OHDSI/CohortDiagnostics#1125] opened 2024-07-16 18:21 UTC
I managed to generate cohort diagnostics sqlite file and are trying to display the result in R Shiny. However, I faced error when I try to run the codes `cohortDiagnostics::launchDiagnosticsExplorer(sqliteDbPath = "MergedCohortDiagnosticsData.sqlite")` Below is the error message. 

Error in `DatabaseConnector::getTableNames()`:
! Pool, R6 connection not supported

It is very strange that I was able to visualize results using the same codes a few months ago. Wonder if there is any change in my R environment. 

Thank you for any advice!

**Comment by azimov** [comment] 2024-07-16 21:54
@SamuelFan1215 have you updated to the latest version of OhdsiShinyModules? This was hot fixed yesterday and was caused by some changes in DatabaseConnector

**Comment by azimov** [comment] 2024-09-30 21:34
Closed as likely resolved in OSM release  problem

**Closed by azimov** 2024-09-30 21:34 UTC
