### ISSUE TITLE
Index Event Breakdown errors when cohort have 0 count

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#1034] opened 2023-02-16 02:18 UTC
When all cohorts being run have 0 record count, CD executions fails on index event breakdown as follows. Instead it should continue with no results in index event breakdown. Or (better) it should not run diagnostics that are not informative when cohorts have 0 count.

> 2023-02-15 21:12:55	[Thread 4]	TRACE	CohortDiagnostics	makeDataExportable	 - Ensuring data is exportable: index_event_breakdown
> 2023-02-15 21:12:55	[Thread 4]	TRACE	CohortDiagnostics	makeDataExportable	 - Ensuring data is exportable: index_event_breakdown
> 2023-02-15 21:12:55	[Thread 4]	TRACE	CohortDiagnostics	makeDataExportable	  - Found in table index_event_breakdown the following fields: databaseId
> 2023-02-15 21:12:55	[Thread 4]	TRACE	CohortDiagnostics	makeDataExportable	  - Found in table index_event_breakdown the following fields: databaseId
> 2023-02-15 21:12:55	[Thread 4]	FATAL	CohortDiagnostics	makeDataExportable	 - Cannot find required field index_event_breakdown - conceptId, conceptCount, subjectCount, cohortId, domainField, domainTable.
> 2023-02-15 21:12:55	[Thread 4]	FATAL	CohortDiagnostics	makeDataExportable	 - Cannot find required field index_event_breakdown - conceptId, conceptCount, subjectCount, cohortId, domainField, domainTable.

**Comment by azimov** [comment] 2024-10-01 17:48
Closing as I Could not reproduce in the latest release. Please re-open if you find this again

**Closed by azimov** 2024-10-01 17:48 UTC
