### ISSUE TITLE
Index event breakdown is missing - show as percent

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortDiagnostics#976] opened 2022-10-11 18:55 UTC
Table headers are missing cohort count (person count or record count)

![image](https://user-images.githubusercontent.com/13936600/195175587-026f2a55-274e-46d2-9247-4d4478a70963.png)

show as percent makes interpretation easier

![image](https://user-images.githubusercontent.com/13936600/195175655-df8e9496-cc6e-428b-af7d-650ff714fd26.png)

Show as percent is calculated based

**Comment by azimov** [comment] 2022-10-12 16:21
Duplicate of #933 - this issue is not going to be resolved by adding the button back

**Closed by azimov** 2022-10-12 16:21 UTC
Labels: duplicate
