### ISSUE TITLE
Error when extracting `included_source_concept` table to CSV

### ISSUE THREAD

**Issue by msuchard** [OHDSI/CohortDiagnostics#514] opened 2021-08-18 19:04 UTC
A colleague notes the following error (postgresql server, attempting `assessPhenotypes` in `LegendT2dm`):

```
hread: Main
Message:  Error: Error executing SQL: org.postgresql.util.PSQLException: ERROR: integer out of range An error report has been created at [EDITED FOR PRIVACY] [90mRun `rlang::last_error()` to see where the error occurred.[39m 
Level:  FATAL
Time:  2021-08-08 01:45:28

Stack trace:
14: stop(fallback)
13: signal_abort(cnd)
12: abort(paste("Error executing SQL:", message, paste("An error report has been created at ", fileName), sep = "\n"), 
11: .createErrorReport(connection@dbms, err$message, sqlStatement, errorReportFile)
10: value[[3]](cond)
9: tryCatchOne(expr, names, parentenv, handlers[[1]])
8: tryCatchList(expr, classes, parentenv, handlers)
7: tryCatch({
    startQuery <- Sys.time()
    lowLevelExecuteSql(connection, sqlStatement)
    if (profile) {
       
6: executeSql(connection = connection, sql = sql, profile = profile, progressBar = progressBar, reportOverallTime = re
5: DatabaseConnector::renderTranslateExecuteSql(connection = connection, sql = sql, tempEmulationSchema = tempEmulatio
4: runConceptSetDiagnostics(connection = connection, tempEmulationSchema = tempEmulationSchema, cdmDatabaseSchema = cd
3: CohortDiagnostics.R#29: CohortDiagnostics::runCohortDiagnostics(packageName = "LegendT2dm", cohortToCreateFile = pa
2: Assessment.R#84: runExposureCohortDiagnostics(connectionDetails, cdmDatabaseSchema, cohortDatabaseSchema, tablePref
1: assessPhenotypes(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema, oracleTempSchema = N

R version:
R version 4.0.5 (2021-03-31)

Platform:
x86_64-w64-mingw32

Attached base packages:
- stats
- graphics
- grDevices
- datasets
- utils
- methods
- base

Other attached packages:
- LegendT2dm (0.0.1)
- DatabaseConnector (4.0.2)
```

From the `assessmentLog`: 

```
2021-08-08 01:45:28	[Main thread]	DEBUG	CohortDiagnostics	writeToCsv	creating [PRiVACY]/cohortDiagnosticsExport/included_source_concept.csv
2021-08-08 01:45:28	[Main thread]	FATAL	DatabaseConnector	.createErrorReport	Error: Error executing SQL: org.postgresql.util.PSQLException: ERROR: integer out of range An error report has been created at  [PRiVACY]/errorReportSql.txt [90mRun `rlang::last_error()` to see where the error occurred.[39m 
```

I don't know if this is a `CohortDiagnostics` or `DatabaseConnector` error.   Ideas?  @gowthamrao @schuemie

**Comment by msuchard** [comment] 2021-08-18 19:06
Also, my colleague reports having 64bit concept IDs here.

**Comment by msuchard** [comment] 2021-08-18 19:08
Here's the SQL error report:

```
   "DBMS:
    postgresql

 

    Error:
    org.postgresql.util.PSQLException: ERROR: integer out of range

 

    SQL:
    INSERT INTO concept_ids (concept_id)
                  SELECT DISTINCT source_concept_id
                  FROM inc_src_concepts
 ```

**Comment by msuchard** [comment] 2021-08-18 20:19
@gowthamrao -- I think the solution is to update `CreateConceptIdTable.sql` to read:

```
IF OBJECT_ID('tempdb..@table_name', 'U') IS NOT NULL
	DROP TABLE @table_name;

CREATE TABLE @table_name (concept_id BIGINT);
```

`concept_id` was just `INT`

**Comment by gowthamrao** [comment] 2021-08-28 09:45
Hi @msuchard this is an unusual behavior. concept_id should always be constrained to INT range by design

See DDL https://github.com/OHDSI/CommonDataModel/blob/master/PostgreSQL/OMOP%20CDM%20Results%20postgresql%20ddl.txt

Does you colleague have conceptIds that are not OMOP/OHDSI vocabulary generated? Are there very high conceptId values that belong the BIGINT range i.e. > 2^31-1 (2,147,483,647)

**Comment by gowthamrao** [comment] 2021-09-16 00:51
@msuchard is this still an issue?

**Comment by gowthamrao** [comment] 2021-09-27 02:08
@msuchard  not hearing from you - i am going to assume this is resolved. Closing

**Closed by gowthamrao** 2021-09-27 02:08 UTC
