### ISSUE TITLE
CohortDiagnostics reading from DB Shiny Issue - Empty Database.csv

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortDiagnostics#713] opened 2022-01-11 14:16 UTC
CohortDiagnostics reading from DB Shiny Issue.  Had a DP where all the files had record except the database.csv file.  The files loaded properly to the database.  However the CohortDiagnostics viewer just drops the records - you cannot see evidence for that DP.  Might want to either expose that this is happening to the user or send an error message (there are database_id records that do not have an entry in the database table).

**Comment by azimov** [comment] 2022-01-19 18:52
It sounds like the problem is that the `database.csv` file is not being exported properly or is not transferred by the data partner.

In the first case i'm not sure what would cause this issue or how to resolve it without understanding the DP setup. However, a fix for the second issue is to ensure that `database.csv` is present and populated before allowing results upload.

**Comment by gowthamrao** [comment] 2022-02-09 22:09
I think we need to understand why is the database.csv not populated. https://github.com/OHDSI/CohortDiagnostics/pull/748 will ensure the table structure is right

**Closed** 2022-11-18 19:40 UTC
Labels: bug, db results handling
